# Generated by Django 5.1.15 on 2026-08-14 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured photos get the large hero/parallax treatment on the About page.'),
        ),
    ]
