# Generated by Django 5.1.15 on 2026-08-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='Sunday Service', max_length=200)),
                ('event', models.ForeignKey(blank=True, help_text='Optional — link this program to a specific Event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_programs', to='events.event')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('leader', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='program.service')),
            ],
            options={
                'ordering': ['order', 'time'],
            },
        ),
    ]
