# Generated by Django 6.0.7 on 2026-08-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='series/')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('scripture_refs', models.CharField(blank=True, help_text='e.g. John 3:16-21', max_length=300)),
                ('topic_tags', models.CharField(blank=True, help_text='comma-separated', max_length=300)),
                ('video_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/')),
                ('slides_file', models.FileField(blank=True, null=True, upload_to='sermons/slides/')),
                ('transcript_text', models.TextField(blank=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.series')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='sermons.speaker')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
