# Generated by Django 5.1.15 on 2026-08-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short line under the name, optional', max_length=200),
        ),
    ]
