# Generated by Django 5.1.15 on 2026-08-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_churchsettings_logo_churchsettings_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_business_number',
            field=models.CharField(blank=True, help_text="Your Paybill or Till number. Leave blank until you're registered with Safaricom — the manual instructions section stays hidden until this is filled in.", max_length=20),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='mpesa_business_type',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Till / Buy Goods')], default='paybill', help_text='Determines the manual-payment instructions shown on the Give page', max_length=10),
        ),
    ]
